package za.co.entelect.bootcamp.orm.core.entities;

import lombok.Getter;

@Getter
public enum Country {
    AFGHANISTAN("Afghanistan"),
    ALBANIA("Albania"),
    ALGERIA("Algeria"),
    AMERICAN_SAMOA("American Samoa"),
    ANDORRA("Andorra"),
    ANGOLA("Angola"),
    ANGUILLA("Anguilla"),
    ANTARCTICA("Antarctica"),
    ARGENTINA("Argentina"),
    ARMENIA("Armenia"),
    ARUBA("Aruba"),
    AUSTRALIA("Australia"),
    AUSTRIA("Austria"),
    AZERBAIJAN("Azerbaijan"),
    BAHAMAS("Bahamas"),
    BAHRAIN("Bahrain"),
    BANGLADESH("Bangladesh"),
    BARBADOS("Barbados"),
    BELARUS("Belarus"),
    BELGIUM("Belgium"),
    BELIZE("Belize"),
    BENIN("Benin"),
    BERMUDA("Bermuda"),
    BHUTAN("Bhutan"),
    BOLIVIA("Bolivia"),
    BOTSWANA("Botswana"),
    BRAZIL("Brazil"),
    BULGARIA("Bulgaria"),
    BURKINA_FASO("Burkina Faso"),
    BURUNDI("Burundi"),
    CAMBODIA("Cambodia"),
    CAMEROON("Cameroon"),
    CANADA("Canada"),
    CAPE_VERDE("Cape Verde"),
    CHILE("Chile"),
    CHINA("China"),
    COLOMBIA("Colombia"),
    COMOROS("Comoros"),
    CONGO("Congo"),
    COOK_ISLANDS("Cook Islands"),
    COSTA_RICA("Costa Rica"),
    COTE_D_IVOIRE("Côte d'Ivoire"),
    CROATIA("Croatia"),
    CUBA("Cuba"),
    CYPRUS("Cyprus"),
    CZECH_REPUBLIC("Czech Republic"),
    DENMARK("Denmark"),
    DJIBOUTI("Djibouti"),
    DOMINICA("Dominica"),
    ECUADOR("Ecuador"),
    EGYPT("Egypt"),
    EIRE("Eire"),
    EL_SALVADOR("El Salvador"),
    ERITREA("Eritrea"),
    ESTONIA("Estonia"),
    ETHIOPIA("Ethiopia"),
    FALKLANDS("Falklands"),
    FIJI("Fiji"),
    FINLAND("Finland"),
    FRANCE("France"),
    FRENCH_GUIANA("French Guiana"),
    GABON("Gabon"),
    GAMBIA("Gambia"),
    GEORGIA("Georgia"),
    GERMANY("Germany"),
    GIBRALTAR("Gibraltar"),
    GREECE("Greece"),
    GREENLAND("Greenland"),
    GRENADA("Grenada"),
    GUADELOUPE("Guadeloupe"),
    GUAM("Guam"),
    GUATEMALA("Guatemala"),
    GUERNSEY("Guernsey"),
    GUINEA("Guinea"),
    GUINEA_BISSAU("Guinea-Bissau"),
    GUYANA("Guyana"),
    HAITI("Haiti"),
    HONDURAS("Honduras"),
    HONG_KONG("Hong Kong"),
    HUNGARY("Hungary"),
    ICELAND("Iceland"),
    INDIA("India"),
    INDONESIA("Indonesia"),
    IRAN("Iran"),
    IRAQ("Iraq"),
    ISLE_OF_MAN("Isle of Man"),
    ISRAEL("Israel"),
    ITALY("Italy"),
    JAMAICA("Jamaica"),
    JAPAN("Japan"),
    JERSEY("Jersey"),
    JORDAN("Jordan"),
    KAZAKHSTAN("Kazakhstan"),
    KENYA("Kenya"),
    KIRIBATI("Kiribati"),
    KUWAIT("Kuwait"),
    KYRGYZSTAN("Kyrgyzstan"),
    LATVIA("Latvia"),
    LEBANON("Lebanon"),
    LESOTHO("Lesotho"),
    LIBERIA("Liberia"),
    LIBYA("Libya"),
    LIECHTENSTEIN("Liechtenstein"),
    LITHUANIA("Lithuania"),
    LUXEMBOURG("Luxembourg"),
    MACAO("Macao"),
    MACEDONIA("Macedonia"),
    MADAGASCAR("Madagascar"),
    MALAWI("Malawi"),
    MALAYSIA("Malaysia"),
    MALI("Mali"),
    MALTA("Malta"),
    MALVINAS("Malvinas"),
    MARTINIQUE("Martinique"),
    MAURITANIA("Mauritania"),
    MAURITIUS("Mauritius"),
    MAYOTTE("Mayotte"),
    MEXICO("Mexico"),
    MICRONESIA("Micronesia"),
    MOLDOVA("Moldova"),
    MONACO("Monaco"),
    MONTENEGRO("Montenegro"),
    MONTSERRAT("Montserrat"),
    MOROCCO("Morocco"),
    MOZAMBIQUE("Mozambique"),
    MYANMAR("Myanmar"),
    NAMIBIA("Namibia"),
    NAURU("Nauru"),
    NEPAL("Nepal"),
    NETHERLANDS("Netherlands"),
    NEW_CALEDONIA("New Caledonia"),
    NEW_ZEALAND("New Zealand"),
    NICARAGUA("Nicaragua"),
    NIGER("Niger"),
    NIGERIA("Nigeria"),
    NIUE("Niue"),
    NORTH_KOREA("North Korea"),
    OMAN("Oman"),
    PAKISTAN("Pakistan"),
    PANAMA("Panama"),
    PARAGUAY("Paraguay"),
    PERU("Peru"),
    PHILIPPINES("Philippines"),
    PITCAIRN("Pitcairn"),
    POLAND("Poland"),
    PORTUGAL("Portugal"),
    PUERTO_RICO("Puerto Rico"),
    QATAR("Qatar"),
    REUNION("Réunion"),
    RUSSIA("Russia"),
    RWANDA("Rwanda"),
    SAINT_HELENA("Saint Helena"),
    SAINT_LUCIA("Saint Lucia"),
    SAMOA("Samoa"),
    SAN_MARINO("San Marino"),
    SAUDI_ARABIA("Saudi Arabia"),
    SENEGAL("Senegal"),
    SERBIA("Serbia"),
    SEYCHELLES("Seychelles"),
    SIERRA_LEONE("Sierra Leone"),
    SINGAPORE("Singapore"),
    SLOVAKIA("Slovakia"),
    SLOVENIA("Slovenia"),
    SOMALIA("Somalia"),
    SOUTH_AFRICA("South Africa"),
    SOUTH_GEORGIA("South Georgia"),
    SOUTH_KOREA("South Korea"),
    SPAIN("Spain"),
    SRI_LANKA("Sri Lanka"),
    SUDAN("Sudan"),
    SURINAME("Suriname"),
    SWAZILAND("Swaziland"),
    SWEDEN("Sweden"),
    SWITZERLAND("Switzerland"),
    SYRIA("Syria"),
    TAIWAN("Taiwan"),
    TAJIKISTAN("Tajikistan"),
    TANZANIA("Tanzania"),
    THAILAND("Thailand"),
    TIMOR_LESTE("Timor-Leste"),
    TOGO("Togo"),
    TONGA("Tonga"),
    TRINIDAD("Trinidad"),
    TUNISIA("Tunisia"),
    TURKEY("Turkey"),
    TUVALU("Tuvalu"),
    UGANDA("Uganda"),
    UNITED_KINGDOM("United Kingdom"),
    UNITED_STATES("United States"),
    URUGUAY("Uruguay"),
    UZBEKISTAN("Uzbekistan"),
    VANUATU("Vanuatu"),
    VATICAN_CITY("Vatican City"),
    VENEZUELA("Venezuela"),
    VIETNAM("Vietnam"),
    VIRGIN_ISLANDS("Virgin Islands"),
    WESTERN_SAHARA("Western Sahara"),
    ZAMBIA("Zambia"),
    ZIMBABWE("Zimbabwe");

    private String name;

    Country(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return this.name;
    }

    public static Country fromString(String text) {
        for (Country country : Country.values()) {
            if (text.trim().equalsIgnoreCase(country.getName())) {
                return country;
            }
        }

        return null;
    }
}
